@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< Updated upstream
REM Generated by Vivado on Sat May 02 01:44:50 +0530 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
=======
REM Generated by Vivado on Sun May 03 11:31:42 +0530 2026
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
>>>>>>> Stashed changes
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0

REM compile VHDL design sources
echo "xvhdl --incr --relax -prj TB_RCA_4_vhdl.prj"
call xvhdl  --incr --relax -prj TB_RCA_4_vhdl.prj -log xvhdl.log
call type xvhdl.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
