@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri May 01 13:30:57 +0530 2026
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim TB_Nano_Processor_7_Seg_behav -key {Behavioral:Final:Functional:TB_Nano_Processor_7_Seg} -tclbatch TB_Nano_Processor_7_Seg.tcl -view C:/Users/USER/Desktop/Nanoprocessor-Design-Compettition-main/src/project_1/TB_Nano_Processor_7_Seg_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
