@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< Updated upstream
REM Generated by Vivado on Sat May 02 01:44:52 +0530 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
=======
REM Generated by Vivado on Sun May 03 11:31:54 +0530 2026
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
>>>>>>> Stashed changes
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim TB_RCA_4_behav -key {Behavioral:Final:Functional:TB_RCA_4} -tclbatch TB_RCA_4.tcl -view C:/Users/VICTUS/OneDrive/Desktop/COADD/Nanoprocessor-Design/Nanoprocessor-Design-Compettition-main/src/project_1/TB_Nano_Processor_7_Seg_behav.wcfg -log simulate.log"
call xsim  TB_RCA_4_behav -key {Behavioral:Final:Functional:TB_RCA_4} -tclbatch TB_RCA_4.tcl -view C:/Users/VICTUS/OneDrive/Desktop/COADD/Nanoprocessor-Design/Nanoprocessor-Design-Compettition-main/src/project_1/TB_Nano_Processor_7_Seg_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
